Repository brain-tec/stock-logistics-workflow, pull requests merged in 2022-09, with the labels that each got.

#602 Syncing from upstream OCA/stock-logistics-workflow (13.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_customer_ref/odoo/addons/stock_picking_customer_ref
  setup/stock_picking_customer_ref/setup.py
  stock_picking_batch_extended_account/__manifest__.py
  stock_picking_batch_extended_account/migrations/13.0.1.1.0/post-migration.py
  stock_picking_customer_ref/README.rst
  stock_picking_customer_ref/__init__.py
  stock_picking_customer_ref/__manifest__.py
  stock_picking_customer_ref/i18n/de.po
  stock_picking_customer_ref/i18n/es.po
  stock_picking_customer_ref/i18n/fr.po
  stock_picking_customer_ref/i18n/hr.po
  stock_picking_customer_ref/i18n/it.po
  stock_picking_customer_ref/i18n/nl.po
  stock_picking_customer_ref/i18n/pt.po
  stock_picking_customer_ref/i18n/pt_BR.po
  stock_picking_customer_ref/i18n/sl_SI.po
  stock_picking_customer_ref/i18n/stock_picking_customer_ref.pot
  stock_picking_customer_ref/models/__init__.py
  stock_picking_customer_ref/models/stock_picking.py
  stock_picking_customer_ref/readme/CONTRIBUTORS.rst
  stock_picking_customer_ref/readme/CREDITS.rst
  stock_picking_customer_ref/readme/DESCRIPTION.rst
  stock_picking_customer_ref/readme/USAGE.rst
  stock_picking_customer_ref/static/description/icon.png
  stock_picking_customer_ref/static/description/index.html
  stock_picking_customer_ref/tests/__init__.py
  stock_picking_customer_ref/tests/test_stock_picking_customer_ref.py
  stock_picking_customer_ref/views/stock_picking_view.xml
  stock_picking_return_restricted_qty/__manifest__.py
  stock_picking_return_restricted_qty/wizard/stock_picking_return.py
Labels: 13.0

#603 Syncing from upstream OCA/stock-logistics-workflow (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_lot_scrap/odoo/addons/stock_lot_scrap
  setup/stock_lot_scrap/setup.py
  stock_lot_scrap/README.rst
  stock_lot_scrap/__init__.py
  stock_lot_scrap/__manifest__.py
  stock_lot_scrap/i18n/de.po
  stock_lot_scrap/i18n/es.po
  stock_lot_scrap/i18n/fr.po
  stock_lot_scrap/i18n/hr.po
  stock_lot_scrap/i18n/it.po
  stock_lot_scrap/i18n/pt.po
  stock_lot_scrap/i18n/pt_BR.po
  stock_lot_scrap/i18n/sl.po
  stock_lot_scrap/i18n/stock_lot_scrap.pot
  stock_lot_scrap/models/__init__.py
  stock_lot_scrap/models/stock_production_lot.py
  stock_lot_scrap/models/stock_scrap.py
  stock_lot_scrap/readme/CONFIGURE.rst
  stock_lot_scrap/readme/CONTRIBUTORS.rst
  stock_lot_scrap/readme/DESCRIPTION.rst
  stock_lot_scrap/readme/USAGE.rst
  stock_lot_scrap/static/description/icon.png
  stock_lot_scrap/static/description/index.html
  stock_lot_scrap/tests/__init__.py
  stock_lot_scrap/tests/test_stock_lot_scrap.py
  stock_restrict_lot/__manifest__.py
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/tests/test_restrict_lot.py
Labels: 14.0

#605 Syncing from upstream OCA/stock-logistics-workflow (12.0)
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  sale_order_global_stock_route/__manifest__.py
  stock_move_line_auto_fill/__manifest__.py
  stock_picking_back2draft/__manifest__.py
  stock_picking_batch_extended/README.rst
  stock_picking_batch_extended/__manifest__.py
  stock_picking_batch_extended/static/description/index.html
  stock_picking_filter_lot/__manifest__.py
  stock_picking_invoice_link/__manifest__.py
  stock_picking_mass_action/__manifest__.py
  stock_picking_package_preparation/__manifest__.py
  stock_picking_package_preparation_line/__manifest__.py
  stock_picking_return_lot/__manifest__.py
  stock_picking_return_restricted_qty/__manifest__.py
  stock_picking_sale_order_link/__manifest__.py
  stock_shifting_end_of_lot/__manifest__.py
Labels: 12.0

#606 Syncing from upstream OCA/stock-logistics-workflow (15.0)
  README.md
  stock_picking_purchase_order_link/__manifest__.py
  stock_picking_purchase_order_link/models/stock_picking.py
Labels: 15.0

#587 [t130721] add automatic sequence in goods receipt
  setup/stock_picking_product_generate_sequence/odoo/addons/stock_picking_product_generate_sequence
  setup/stock_picking_product_generate_sequence/setup.py
  stock_picking_product_generate_sequence/__init__.py
  stock_picking_product_generate_sequence/__manifest__.py
  stock_picking_product_generate_sequence/data/stock_picking_product_sequence.xml
  stock_picking_product_generate_sequence/models/__init__.py
  stock_picking_product_generate_sequence/models/product_template.py
  stock_picking_product_generate_sequence/models/stock_move_line.py
  stock_picking_product_generate_sequence/readme/CONTRIBUTORS.rst
  stock_picking_product_generate_sequence/readme/DESCRIPTION.rst
  stock_picking_product_generate_sequence/views/product_template_views.xml
  stock_picking_product_generate_sequence/views/stock_move_line_views.xml
Labels: 15.0.project_sah_650

#607 Syncing from upstream OCA/stock-logistics-workflow (14.0)
  README.md
  sale_line_returned_qty/README.rst
  sale_line_returned_qty/__init__.py
  sale_line_returned_qty/__manifest__.py
  sale_line_returned_qty/i18n/sale_line_returned_qty.pot
  sale_line_returned_qty/models/__init__.py
  sale_line_returned_qty/models/sale_order_line.py
  sale_line_returned_qty/readme/CONTRIBUTORS.rst
  sale_line_returned_qty/readme/DESCRIPTION.rst
  sale_line_returned_qty/static/description/icon.png
  sale_line_returned_qty/static/description/index.html
  sale_line_returned_qty/tests/__init__.py
  sale_line_returned_qty/tests/test_sale_line_returned_qty.py
  sale_line_returned_qty/views/sale_order_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_line_returned_qty/odoo/addons/sale_line_returned_qty
  setup/sale_line_returned_qty/setup.py
Labels: 14.0

#608 Syncing from upstream OCA/stock-logistics-workflow (15.0)
  README.md
  sale_line_returned_qty/README.rst
  sale_line_returned_qty/__init__.py
  sale_line_returned_qty/__manifest__.py
  sale_line_returned_qty/i18n/sale_line_returned_qty.pot
  sale_line_returned_qty/models/__init__.py
  sale_line_returned_qty/models/sale_order_line.py
  sale_line_returned_qty/readme/CONTRIBUTORS.rst
  sale_line_returned_qty/readme/DESCRIPTION.rst
  sale_line_returned_qty/static/description/icon.png
  sale_line_returned_qty/static/description/index.html
  sale_line_returned_qty/tests/__init__.py
  sale_line_returned_qty/tests/test_sale_line_returned_qty.py
  sale_line_returned_qty/views/sale_order_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_line_returned_qty/odoo/addons/sale_line_returned_qty
  setup/sale_line_returned_qty/setup.py
Labels: 15.0

#609 Syncing from upstream OCA/stock-logistics-workflow (13.0)
  README.md
  purchase_stock_picking_invoice_link/__manifest__.py
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
Labels: 13.0

#610 Syncing from upstream OCA/stock-logistics-workflow (14.0)
  README.md
  purchase_stock_picking_invoice_link/__manifest__.py
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
Labels: 14.0

#611 Syncing from upstream OCA/stock-logistics-workflow (13.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_picking_batch_extended_account_sale_type/odoo/addons/stock_picking_batch_extended_account_sale_type
  setup/stock_picking_batch_extended_account_sale_type/setup.py
  stock_picking_batch_extended_account_sale_type/__init__.py
  stock_picking_batch_extended_account_sale_type/__manifest__.py
  stock_picking_batch_extended_account_sale_type/i18n/es.po
  stock_picking_batch_extended_account_sale_type/i18n/stock_picking_batch_extended_account_sale_type.pot
  stock_picking_batch_extended_account_sale_type/models/__init__.py
  stock_picking_batch_extended_account_sale_type/models/res_partner.py
  stock_picking_batch_extended_account_sale_type/models/sale_order_type.py
  stock_picking_batch_extended_account_sale_type/models/stock_batch_picking.py
  stock_picking_batch_extended_account_sale_type/static/description/icon.png
  stock_picking_batch_extended_account_sale_type/tests/__init__.py
  stock_picking_batch_extended_account_sale_type/tests/test_stock_picking_batch_extended_account_sale_type.py
  stock_picking_batch_extended_account_sale_type/views/sale_order_type_views.xml
Labels: 13.0

#612 Syncing from upstream OCA/stock-logistics-workflow (12.0)
  stock_dropshipping_whole_supplier/i18n/pt_BR.po
Labels: 12.0

#613 Syncing from upstream OCA/stock-logistics-workflow (15.0)
  stock_picking_send_by_mail/i18n/pt.po
Labels: 15.0

#614 Syncing from upstream OCA/stock-logistics-workflow (15.0)
  stock_picking_send_by_mail/i18n/pt.po
Labels: 15.0

#616 [t132059] [saht380] Invoicing with herbs & farmers
  setup/stock_picking_invoice_link/odoo/addons/stock_picking_invoice_link
  setup/stock_picking_invoice_link/setup.py
  stock_picking_invoice_link/README.rst
  stock_picking_invoice_link/__init__.py
  stock_picking_invoice_link/__manifest__.py
  stock_picking_invoice_link/i18n/ca.po
  stock_picking_invoice_link/i18n/de.po
  stock_picking_invoice_link/i18n/es.po
  stock_picking_invoice_link/i18n/es_MX.po
  stock_picking_invoice_link/i18n/fi.po
  stock_picking_invoice_link/i18n/fr.po
  stock_picking_invoice_link/i18n/hr.po
  stock_picking_invoice_link/i18n/it.po
  stock_picking_invoice_link/i18n/nl_NL.po
  stock_picking_invoice_link/i18n/pt.po
  stock_picking_invoice_link/i18n/pt_BR.po
  stock_picking_invoice_link/i18n/sl.po
  stock_picking_invoice_link/i18n/stock_picking_invoice_link.pot
  stock_picking_invoice_link/i18n/tr.po
  stock_picking_invoice_link/i18n/tr_TR.po
  stock_picking_invoice_link/models/__init__.py
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/models/stock_move.py
  stock_picking_invoice_link/models/stock_picking.py
  stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  stock_picking_invoice_link/readme/DESCRIPTION.rst
  stock_picking_invoice_link/readme/USAGE.rst
  stock_picking_invoice_link/static/description/icon.png
  stock_picking_invoice_link/static/description/index.html
  stock_picking_invoice_link/tests/__init__.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/views/account_invoice_view.xml
  stock_picking_invoice_link/views/stock_view.xml
Labels: 15.0.project_sah_650

#617 Syncing from upstream OCA/stock-logistics-workflow (15.0)
  stock_no_negative/i18n/fr.po
Labels: 15.0
